name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 生成贪吃蛇SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake.svg
            snake-dark.svg?palette=github-dark

      - name: 提交&推送文件
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "update snake gif"
          git push